# This file was generated by GoReleaser. DO NOT EDIT.
cask "tracemill" do
  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}/tracemill"],
      must_succeed: false,
      print_stderr: true
  end

  name "tracemill"
  desc "Stateful, high-fidelity security and o11y telemetry generation engine"
  homepage "https://tracemill.io"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tracemill"

  on_macos do
    on_intel do
      url "https://dl.tracemill.io/cli/#{version}/tracemill_darwin_amd64.tar.gz",
        verified: "dl.tracemill.io"
      sha256 "30e1b127c8df70d7908bb6ab261d7c022c9a60bf532bdee3e982e8e61ce6b9f2"
    end
    on_arm do
      url "https://dl.tracemill.io/cli/#{version}/tracemill_darwin_arm64.tar.gz",
        verified: "dl.tracemill.io"
      sha256 "034298f4f36e6fe65ef956a17a24741d02e0bd571dd040e7ce2eff30e4ecf5d3"
    end
  end

  on_linux do
    on_intel do
      url "https://dl.tracemill.io/cli/#{version}/tracemill_linux_amd64.tar.gz",
        verified: "dl.tracemill.io"
      sha256 "e0e401228be16747cee87202a4a2ecb7660b98cd5b9d712367ec48b0df02786b"
    end
    on_arm do
      url "https://dl.tracemill.io/cli/#{version}/tracemill_linux_arm64.tar.gz",
        verified: "dl.tracemill.io"
      sha256 "8eb01eb3ca82642e38b31fc47a8740779494e3e9d68bdfa3595f5ab81333b146"
    end
  end

  # No zap stanza required
end
