# This file was generated by GoReleaser. DO NOT EDIT.
cask "tracemill" do
  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}/tracemill"],
      must_succeed: false,
      print_stderr: true
  end

  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "868a7ce0cdcbd4a88bd6ca3cb10a709c4d05769ac74af2bf3234641149806454"
      url "https://dl.tracemill.io/cli/#{version}/tracemill_darwin_amd64.tar.gz",
        verified: "dl.tracemill.io"
    end
    on_arm do
      sha256 "4843b7326a3bc7c2527667334a0a5f567efa68cdc2cbb111c96cd9282ce021d0"
      url "https://dl.tracemill.io/cli/#{version}/tracemill_darwin_arm64.tar.gz",
        verified: "dl.tracemill.io"
    end
  end

  on_linux do
    on_intel do
      sha256 "3cb70d93e471ea15c66216bb81c05cc4bec22aeb32e86f6b8f1f7691edb39b66"
      url "https://dl.tracemill.io/cli/#{version}/tracemill_linux_amd64.tar.gz",
        verified: "dl.tracemill.io"
    end
    on_arm do
      sha256 "9d9034abce9c4c870ecab31b39a22672bf67d284acf652b2d75b3e4107aa49a8"
      url "https://dl.tracemill.io/cli/#{version}/tracemill_linux_arm64.tar.gz",
        verified: "dl.tracemill.io"
    end
  end

  name "tracemill"
  desc "Stateful, high-fidelity security and o11y telemetry generation engine"
  homepage "https://tracemill.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tracemill"

  # No zap stanza required

end
