# This file was generated by GoReleaser. DO NOT EDIT.
cask "tracemill" do
  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}/tracemill"],
      must_succeed: false,
      print_stderr: true
  end

  version "0.4.7"

  on_macos do
    on_intel do
      sha256 "12bfb9b4b15763a36620d1f92b3659e522b59658d82801d556e7863d669f6d99"
      url "https://dl.tracemill.io/cli/#{version}/tracemill_darwin_amd64.tar.gz",
        verified: "dl.tracemill.io"
    end
    on_arm do
      sha256 "25ef10d36b6c54a3600f8a6baebce0fffe8bb7239dae4279452fee2016c5875f"
      url "https://dl.tracemill.io/cli/#{version}/tracemill_darwin_arm64.tar.gz",
        verified: "dl.tracemill.io"
    end
  end

  on_linux do
    on_intel do
      sha256 "c70fe641e56cd1121a083e8b22a12b35e0fa25dba76c618d4dcdd7cb2637f513"
      url "https://dl.tracemill.io/cli/#{version}/tracemill_linux_amd64.tar.gz",
        verified: "dl.tracemill.io"
    end
    on_arm do
      sha256 "0be2ddfeaecb4faa3fd4876981284721d33f1404b9587f04597237c834b15a05"
      url "https://dl.tracemill.io/cli/#{version}/tracemill_linux_arm64.tar.gz",
        verified: "dl.tracemill.io"
    end
  end

  name "tracemill"
  desc "Stateful, high-fidelity security and o11y telemetry generation engine"
  homepage "https://tracemill.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tracemill"

  # No zap stanza required

end
