# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tracemill < Formula
  desc "Stateful, high-fidelity security and o11y telemetry generation engine"
  homepage "https://tracemill.io"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tracemill/platform/releases/download/v0.1.1/tracemill_darwin_amd64.tar.gz"
      sha256 "e8658ce535723e89460234c699b18bccc16f1ec6ed06c637bf11faba5efefa64"

      define_method(:install) do
        bin.install "tracemill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tracemill/platform/releases/download/v0.1.1/tracemill_darwin_arm64.tar.gz"
      sha256 "4a0e8f3e932d225c5fe362fc4242017f586345e841dd9efe5f624fdd0c299da4"

      define_method(:install) do
        bin.install "tracemill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tracemill/platform/releases/download/v0.1.1/tracemill_linux_amd64.tar.gz"
      sha256 "6ddd78d2ae9dbfd7fb51ff6d4c78a0efd316b337842ff670275fabf787bc8eb4"
      define_method(:install) do
        bin.install "tracemill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tracemill/platform/releases/download/v0.1.1/tracemill_linux_arm64.tar.gz"
      sha256 "fda159d76c99b975292e21468b10aa6ad6c7c91b940cd362dacb3671a9363739"
      define_method(:install) do
        bin.install "tracemill"
      end
    end
  end

  test do
    system "#{bin}/tracemill", "--help"
  end
end
